### ISSUE TITLE
Unexpected token {

### ISSUE THREAD

**Issue by Rattlyy** [wvffle/minecraft-packet-debugger#5]
```
root@AsAHost1:~# mcpd
/usr/local/lib/node_modules/mcpd/index.js:139
    } catch {
            ^

SyntaxError: Unexpected token {
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/mcpd/bin/mcpd.js:16:13)

```

**Comment by wvffle** [comment]
Use node `12.10.0` or higer

**Comment by wvffle** [comment]
@zRattly, did it work?

**Comment by zRattly** [comment]
already using latest node version

**Comment by wvffle** [comment]
Which one? Can you provide me `node --version` output?

**Comment by Rattlyy** [comment]
8.0, updating

**Comment by wvffle** [comment]
Closing due to inactivity. If upgrading node version to 12.10.0+ didn't work then please reopen.
